import { BaseAgent } from './base';
import { AgentTask } from './taskStorage';
import { exec } from 'child_process';
import { promisify } from 'util';
import { promises as fs } from 'fs';
import {
  createSandbox,
  addFeatureToSandbox,
  testFeature,
  evaluateSandboxReadiness,
  markSandboxForMerge,
  type SandboxEnvironment,
  type SandboxFeature,
} from '../sandboxEnvironmentService';
import { createPRForSandbox } from '../automatedPRService';
import {
  analyzeCodeForIssues,
  type SecurityIssue,
  type PerformanceIssue,
  type CodeQualityIssue,
} from '../codeAnalysisService';

const execAsync = promisify(exec);

export interface IssueIdentification {
  issueType: 'bug' | 'enhancement' | 'security' | 'performance';
  description: string;
  affectedFiles: string[];
  severity: 'low' | 'medium' | 'high' | 'critical';
}

export interface CodeFix {
  description: string;
  files: string[];
  changes: string;
}

class CodingAgent extends BaseAgent {
  constructor() {
    super(
      'coding',
      'An agent that can write and understand code, perform automated bug fixes, and create pull requests.'
    );
  }

  protected async executeInternal(task: string): Promise<string> {
    this.log(`CodingAgent received task: ${task}`);
    // In the future, this could be a call to a code generation model
    return `I have received the coding task: '${task}'. I will work on it.`;
  }

  /**
   * Full automated fix lifecycle:
   * 1. Identify documented issues
   * 2. Generate code fix
   * 3. Execute fix in sandbox for testing
   * 4. Create PR upon successful verification
   */
  async performAutomatedFixLifecycle(params: {
    repositoryPath: string;
    issueSource?: 'error_log' | 'code_analysis' | 'manual';
  }): Promise<{
    success: boolean;
    sandboxId?: string;
    prUrl?: string;
    message: string;
  }> {
    try {
      console.log('Starting automated fix lifecycle...');

      // Step 1: Identify issues from code analysis
      const issues = await this.identifyIssues(params.repositoryPath);
      if (issues.length === 0) {
        return {
          success: false,
          message: 'No issues identified for automated fixing',
        };
      }

      console.log(`Identified ${issues.length} issues for fixing`);

      // Select high-priority issue
      const issueToFix = issues.find((i) => i.severity === 'high') || issues[0];

      // Step 2: Generate a code fix
      const fix = await this.generateCodeFix(issueToFix);

      // Step 3: Execute fix in sandbox environment
      const sandbox = await createSandbox({
        name: `fix-${issueToFix.issueType}-${Date.now()}`,
        description: `Automated fix for: ${issueToFix.description}`,
        createdBy: 'milla',
      });

      console.log(`Created sandbox: ${sandbox.id}`);

      // Add feature to sandbox
      const feature = await addFeatureToSandbox(sandbox.id, {
        name: `Fix: ${issueToFix.description}`,
        description: fix.description,
        files: fix.files,
      });

      if (!feature) {
        return {
          success: false,
          message: 'Failed to add feature to sandbox',
        };
      }

      // Step 4: Run tests in sandbox
      const testResults = await Promise.all([
        testFeature(sandbox.id, feature.id, 'unit'),
        testFeature(sandbox.id, feature.id, 'integration'),
      ]);

      const allTestsPassed = testResults.every((result) => result.passed);

      if (!allTestsPassed) {
        return {
          success: false,
          sandboxId: sandbox.id,
          message: `Tests failed in sandbox. Feature status: ${feature.status}`,
        };
      }

      // Evaluate sandbox readiness
      const readiness = evaluateSandboxReadiness(sandbox.id);
      if (!readiness.ready) {
        return {
          success: false,
          sandboxId: sandbox.id,
          message: `Sandbox not ready for merge: ${readiness.reasons.join(', ')}`,
        };
      }

      // Mark sandbox for merge
      await markSandboxForMerge(sandbox.id);

      // Step 5: Create PR via automated PR service
      const prRequest = await createPRForSandbox({
        sandboxId: sandbox.id,
        title: `Automated fix: ${issueToFix.description}`,
        description: `## Automated Code Fix\n\n**Issue Type:** ${issueToFix.issueType}\n**Severity:** ${issueToFix.severity}\n\n${fix.description}\n\n**Affected Files:**\n${fix.files.map((f) => `- ${f}`).join('\n')}\n\n**Test Results:**\n✅ All tests passed\n\nThis PR was automatically generated by the CodingAgent.`,
        branch: sandbox.branchName,
        files: fix.files,
      });

      console.log(`Created PR request: ${prRequest.id}`);

      return {
        success: true,
        sandboxId: sandbox.id,
        prUrl: prRequest.prUrl,
        message: `Successfully created automated fix and PR for: ${issueToFix.description}`,
      };
    } catch (error) {
      console.error('Error in automated fix lifecycle:', error);
      return {
        success: false,
        message: `Error: ${error instanceof Error ? error.message : 'Unknown error'}`,
      };
    }
  }

  /**
   * Identify issues from error logs or code analysis
   */
  private async identifyIssues(
    repositoryPath: string
  ): Promise<IssueIdentification[]> {
    const issues: IssueIdentification[] = [];

    try {
      // For now, we'll use code analysis service to identify issues
      // In the future, this could also parse error logs
      const analysis = await analyzeCodeForIssues({
        repositoryPath,
        focusAreas: ['security', 'performance', 'quality'],
      });

      // Convert security issues
      analysis.securityIssues.forEach((issue: SecurityIssue) => {
        issues.push({
          issueType: 'security',
          description: issue.description,
          affectedFiles: issue.file ? [issue.file] : [],
          severity: issue.severity === 'critical' ? 'critical' : issue.severity,
        });
      });

      // Convert performance issues
      analysis.performanceIssues.forEach((issue: PerformanceIssue) => {
        issues.push({
          issueType: 'performance',
          description: issue.description,
          affectedFiles: issue.file ? [issue.file] : [],
          severity: issue.severity,
        });
      });

      // Convert code quality issues
      analysis.codeQualityIssues.forEach((issue: CodeQualityIssue) => {
        issues.push({
          issueType: 'enhancement',
          description: issue.description,
          affectedFiles: issue.file ? [issue.file] : [],
          severity: 'medium',
        });
      });
    } catch (error) {
      console.error('Error identifying issues:', error);
    }

    return issues;
  }

  /**
   * Generate a code fix for an identified issue using AI
   */
  private async generateCodeFix(issue: IssueIdentification): Promise<CodeFix> {
    try {
      // Use AI to generate a code fix based on the issue
      const prompt = `As an expert software engineer, analyze and fix the following ${issue.severity} severity ${issue.issueType} issue:

**Description:** ${issue.description}
**Affected Files:** ${issue.affectedFiles.join(', ')}

Please provide:
1. A clear description of the fix
2. The specific code changes needed
3. Why this fix resolves the issue

Format your response as JSON with keys: description, changes, reasoning`;

      // Use Minimax service for coding tasks
      const { generateMinimaxResponse } = await import(
        '../minimaxService'
      );

      const result = await generateMinimaxResponse(
        prompt,
        {
          conversationHistory: [],
          userName: 'CodingAgent',
        },
        4096 // Higher token limit for code generation
      );

      if (!result.success) {
        throw new Error(result.error || 'Failed to generate fix');
      }

      let aiResponse;
      try {
        aiResponse = JSON.parse(result.content);
      } catch {
        // Fallback if AI doesn't return valid JSON
        aiResponse = {
          description: result.content.slice(0, 200),
          changes: result.content,
          reasoning: 'AI-generated fix',
        };
      }

      return {
        description:
          aiResponse.description ||
          `Fix for ${issue.issueType}: ${issue.description}`,
        files: issue.affectedFiles,
        changes:
          aiResponse.changes ||
          `Automated fix applied to address ${issue.severity} severity ${issue.issueType} issue`,
      };
    } catch (error) {
      console.error('Error generating AI fix, using fallback:', error);
      // Fallback to simple fix description
      return {
        description: `Fix for ${issue.issueType}: ${issue.description}`,
        files: issue.affectedFiles,
        changes: `Automated fix applied to address ${issue.severity} severity ${issue.issueType} issue. Severity: ${issue.severity}. Requires manual review.`,
      };
    }
  }

  /**
   * Handle agent tasks (implements AgentDefinition interface)
   */
  async handleTask(task: AgentTask): Promise<any> {
    console.log(`CodingAgent handling task: ${task.action}`);

    switch (task.action) {
      case 'automated_fix':
        return await this.performAutomatedFixLifecycle({
          repositoryPath: task.payload?.repositoryPath || process.cwd(),
          issueSource: task.payload?.issueSource || 'code_analysis',
        });

      case 'analyze_code':
        return await this.identifyIssues(
          task.payload?.repositoryPath || process.cwd()
        );

      case 'generate_fix':
        return await this.generateCodeFix(task.payload?.issue);

      default:
        return {
          success: false,
          message: `Unknown action: ${task.action}`,
        };
    }
  }
}

export const codingAgent = new CodingAgent();

// ============================================================================
// P2.5: SCPA Self-Correction Logic Stub
// ============================================================================

/**
 * P2.5: Generate fix for agent failure (STUB)
 * This would analyze the error and generate code to fix it
 *
 * @param failureContext - Context about the agent failure
 * @returns Mock code patch object
 */
export async function generateFix(failureContext: any): Promise<{
  success: boolean;
  patch?: {
    files: string[];
    changes: string;
    description: string;
    testPlan: string;
    fileContents?: Record<string, string>;
  };
  error?: string;
}> {
  console.log(`🔧 [SCPA] Generating fix for ${failureContext.agentName}`);
  console.log(`🔧 [SCPA] Error: ${failureContext.error}`);

  let fix: any;

  // 1. Attempt to generate real fix using AI
  try {
    // Dynamic import to avoid circular dependencies if any
    const { generateMinimaxResponse } = await import('../minimaxService');

    const prompt = `You are an expert software engineer.
An agent named "${failureContext.agentName}" failed with the following error:
"${failureContext.error}"

Please analyze this error and generate a code fix.
Return the response as a valid JSON object with the following structure:
{
  "description": "Description of the fix",
  "reasoning": "Why this fixes the issue",
  "files": ["server/agents/${failureContext.agentName}.ts"],
  "changes": "Summary of changes",
  "fileContents": {
      "server/agents/${failureContext.agentName}.ts": "FULL NEW CONTENT OF THE FILE"
  },
  "testPlan": "How to verify this fix"
}
IMPORTANT:
1. Provide the FULL content of the files in fileContents, not just a diff.
2. Ensure the JSON is valid.
3. If you cannot determine the file path, assume "server/agents/${failureContext.agentName}.ts".
`;

    const result = await generateMinimaxResponse(
      prompt,
      {
        conversationHistory: [],
        userName: 'SCPA_System',
      },
      8192 // Large context for full file generation
    );

    if (result.success) {
      try {
        const cleanContent = result.content.replace(/```json/g, '').replace(/```/g, '').trim();
        fix = JSON.parse(cleanContent);
        // Ensure fileContents exists
        if (!fix.fileContents && fix.changes) {
            fix.fileContents = {}; // Fallback will use 'changes' as simple write if single file
        }
        console.log(`✅ [SCPA] AI generated fix for ${failureContext.agentName}`);
      } catch (parseError) {
        console.warn('⚠️ [SCPA] Failed to parse AI response, falling back to mock.', parseError);
      }
    }
  } catch (aiError) {
    console.warn('⚠️ [SCPA] AI service error, falling back to mock.', aiError);
  }

  // 2. Fallback to mock fix if AI failed
  if (!fix) {
    const errorStr = String(failureContext.error);

    if (errorStr.includes('undefined') || errorStr.includes('null')) {
      fix = {
        files: [`server/agents/${failureContext.agentName}.ts`],
        changes: `// Add null check stub`,
        description: 'Added null/undefined safety check',
        testPlan: 'Test with null input, verify no crash and proper fallback',
      };
    } else if (errorStr.includes('timeout') || errorStr.includes('ETIMEDOUT')) {
      fix = {
        files: [`server/agents/${failureContext.agentName}.ts`],
        changes: `// Add retry logic stub`,
        description: 'Added retry logic and increased timeout',
        testPlan: 'Test with slow network, verify retries work',
      };
    } else if (errorStr.includes('parse') || errorStr.includes('JSON')) {
      fix = {
        files: [`server/agents/${failureContext.agentName}.ts`],
        changes: `// Add JSON parse error handling stub`,
        description: 'Added JSON parsing error handling',
        testPlan: 'Test with invalid JSON, verify graceful fallback',
      };
    } else {
      fix = {
        files: [`server/agents/${failureContext.agentName}.ts`],
        changes: `// Add generic error handling stub`,
        description: 'Added comprehensive error handling',
        testPlan: 'Test error scenarios, verify proper logging and fallback',
      };
    }
    console.log(`✅ [SCPA] Mock fix generated for ${failureContext.agentName}`);
  }

  console.log(`📝 [SCPA] Fix description: ${fix.description}`);

  // 3. Production Workflow: Sandbox -> Apply -> Test -> PR
  let sandboxId: string | undefined;
  let originalBranch = 'main'; // Default assumption

  try {
    // Capture current branch to switch back later
    const { stdout } = await execAsync('git rev-parse --abbrev-ref HEAD');
    originalBranch = stdout.trim();
  } catch (e) {
    console.warn('Could not determine current branch, defaulting to main');
  }

  try {
    // 3.1 Create Sandbox
    console.log('📦 [SCPA] Creating sandbox environment...');
    const sandbox = await createSandbox({
        name: `scpa-fix-${Date.now()}`,
        description: `Auto-fix for ${failureContext.agentName}: ${fix.description}`,
        createdBy: 'milla'
    });
    sandboxId = sandbox.id;

    // 3.2 Checkout Branch (CAUTION: This changes the working directory state)
    console.log(`🌿 [SCPA] Checking out branch ${sandbox.branchName}`);
    try {
        // Fetch to ensure we know about the new branch if it was pushed
        await execAsync(`git fetch origin ${sandbox.branchName}`);
        await execAsync(`git checkout ${sandbox.branchName}`);
    } catch (checkoutError) {
        // If git checkout fails (e.g. dirty working directory), we might abort or try to stash?
        // For safety, we abort workflow if we can't switch context cleanly.
        throw new Error(`Failed to checkout sandbox branch: ${checkoutError}`);
    }

    // 3.3 Apply Fix
    console.log('🔧 [SCPA] Applying fix...');
    const applied = await applyFixToCodebase(fix);
    if (!applied) {
        throw new Error('Failed to apply fix to files');
    }

    // 3.4 Run Tests
    console.log('🧪 [SCPA] Verifying fix...');
    const testResult = await runRealTests(fix.files);

    if (testResult.passed) {
        console.log('✅ [SCPA] Tests passed!');

        // 3.5 Commit and Push
        try {
            await execAsync(`git add .`);
            await execAsync(`git commit -m "fix: ${fix.description}"`);
            await execAsync(`git push origin ${sandbox.branchName}`);
        } catch (gitError) {
             throw new Error(`Failed to commit/push: ${gitError}`);
        }

        // 3.6 Create PR
        console.log('🚀 [SCPA] Creating PR...');
        await createPRForSandbox({
            sandboxId: sandbox.id,
            title: `Fix: ${fix.description}`,
            description: `Automated fix for error in ${failureContext.agentName}.\n\nError: ${failureContext.error}\n\nReasoning: ${fix.reasoning || fix.description}`,
            branch: sandbox.branchName,
            files: fix.files
        });

        // Mark ready
        await markSandboxForMerge(sandbox.id);
    } else {
        console.warn('❌ [SCPA] Tests failed:', testResult.output);
        // We return success: false so the caller knows the fix failed verification.
        // We do NOT revert the branch changes here, but we will switch back to original branch.
        return {
            success: false,
            patch: fix,
            error: 'Tests failed after applying fix:\n' + testResult.output
        };
    }

  } catch (workflowError: any) {
    console.error('❌ [SCPA] Workflow failed:', workflowError);
    return {
        success: false,
        patch: fix,
        error: workflowError.message
    };
  } finally {
    // 4. Cleanup: Always switch back to original branch
    try {
        console.log(`🔙 [SCPA] Returning to branch ${originalBranch}`);
        await execAsync(`git checkout ${originalBranch}`);
    } catch (e) {
        console.error(`CRITICAL: Failed to switch back to original branch ${originalBranch}!`, e);
    }
  }

  return {
    success: true,
    patch: fix,
  };
}

/**
 * Helper: Run tests in the current environment
 */
async function runRealTests(files?: string[]): Promise<{ passed: boolean; output: string }> {
  console.log('🧪 [SCPA] Running tests...');
  try {
    // If specific files are provided, target them. Otherwise run all tests.
    // Note: This assumes we are in the root or can reach vitest.
    const cmd = files && files.length > 0
      ? `npx vitest run ${files.join(' ')} --passWithNoTests`
      : 'npx vitest run --passWithNoTests';

    const { stdout, stderr } = await execAsync(cmd);
    return { passed: true, output: stdout + '\n' + stderr };
  } catch (error: any) {
    console.log('❌ [SCPA] Tests failed');
    return { passed: false, output: (error.stdout || '') + '\n' + (error.stderr || '') };
  }
}

/**
 * P2.5: Apply generated fix to codebase
 * This modifies the actual files on disk
 */
export async function applyFixToCodebase(patch: any): Promise<boolean> {
  console.log(`🔧 [SCPA] Applying fix to codebase`);
  console.log(`📁 [SCPA] Files to modify: ${patch.files.join(', ')}`);

  try {
    // If the patch provides full file content in 'changes' (which we will prompt AI for)
    // or if we have a structured patch.
    // For now, assuming patch.changes contains the NEW content for the file.
    // If there are multiple files, this simple logic assumes 'changes' is a map or we handle one file.
    // TODO: Enhance to handle multi-file patches properly.

    if (patch.fileContents) {
        // New format: { fileContents: { 'path/to/file': 'content' } }
        for (const [filepath, content] of Object.entries(patch.fileContents)) {
            await fs.writeFile(filepath, content as string);
            console.log(`✓ Updated ${filepath}`);
        }
    } else if (patch.files.length === 1) {
        // Fallback/Legacy: Single file update
        await fs.writeFile(patch.files[0], patch.changes);
        console.log(`✓ Updated ${patch.files[0]}`);
    } else {
        console.warn('⚠️ [SCPA] Complex patch format not fully supported yet for multiple files without fileContents map.');
        return false;
    }

    console.log(`✅ [SCPA] Fix applied successfully`);
    return true;
  } catch (error) {
    console.error(`❌ [SCPA] Failed to apply fix:`, error);
    return false;
  }
}

// Register the coding agent with the registry for task-based operations
import { registerAgent } from './registry';

registerAgent({
  name: 'CodingAgent',
  description: 'Automated code analysis, bug fixing, and PR creation agent',
  handleTask: async (task: AgentTask) => {
    return await codingAgent.handleTask(task);
  },
});
